### ISSUE TITLE
Where can I buy the todoo watch from? 

### ISSUE THREAD

**Issue by artgod1** [KhalilMrini/CHIC-Todoo#1]
I have an autistic kid and something like this will help a lot.I downloaded the repo and will run it on android but without the watch  we can't use it. 
Thanks

**Comment by KhalilMrini** [comment]
Sorry for the delay in answering. Unfortunately, the Todoo project could not be finished. I would advise you to consult the Octopus watch, which is the closest finished project: https://www.heyjoy.io/
Thank you for your interest, and my apologies.
